#!/bin/bash

set -e

# dependencies: 1password-cli, wl-clipboard (which you should have anyways on wayland)
# JS field injection code for wayland on linux. A modified version of https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/password_fill
javascript_escape() {
    # print the first argument in an escaped way, such that it can safely
    # be used within javascripts double quotes
    # shellcheck disable=SC2001
    sed "s,[\\\\'\"],\\\\&,g" <<< "$1"
}

js() {
cat <<EOF
    function isVisible(elem) {
        var style = elem.ownerDocument.defaultView.getComputedStyle(elem, null);
        if (style.getPropertyValue("visibility") !== "visible" ||
            style.getPropertyValue("display") === "none" ||
            style.getPropertyValue("opacity") === "0") {
            return false;
        }
        return elem.offsetWidth > 0 && elem.offsetHeight > 0;
    };
    function hasPasswordField(form) {
        var inputs = form.getElementsByTagName("input");
        for (var j = 0; j < inputs.length; j++) {
            var input = inputs[j];
            if (input.type == "password") {
                return true;
            }
        }
        return false;
    };
    function loadData2Form (form) {
        var inputs = form.getElementsByTagName("input");
        for (var j = 0; j < inputs.length; j++) {
            var input = inputs[j];
            if (isVisible(input) && (input.type == "text" || input.type == "email")) {
                input.focus();
                input.value = "$(javascript_escape "${USERNAME}")";
                input.dispatchEvent(new Event('change'));
                input.blur();
            }
            if (input.type == "password") {
                input.focus();
                input.value = "$(javascript_escape "${PASSWORD}")";
                input.dispatchEvent(new Event('change'));
                input.blur();
            }
        }
    };
    var forms = document.getElementsByTagName("form");
    for (i = 0; i < forms.length; i++) {
        if (hasPasswordField(forms[i])) {
            loadData2Form(forms[i]);
        }
    }
EOF
}

QUTE_URL="https://github.com"
URL=$(echo "$QUTE_URL" | awk -F/ '{print $3}' | sed 's/www.//g')

echo "message-info 'Looking for password for $URL...'" >> $QUTE_FIFO

# Ensure op CLI is installed and configured
# TOKEN=$(op signin --raw)
ITEM=$(op item get $URL) || $>> $QUTE_FIFO

echo $ITEM

USERNAME=$(echo $ITEM | grep -oE "username: [^ ]+ " | sed -E "s/username: (\S+)\s/\1/")
PASSWORD=$(echo $ITEM | grep -oE "password: [^ ]+ " | head -n 1 | sed -E "s/password: (\S+)\s/\1/")
TOTP=$(echo $ITEM | grep -oE "one-time password: [^ ]+ " | head -n 1 | sed -E "s/one-time password: (\S+)\s/\1/")


echo $USERNAME
echo $PASSWORD
echo $TOTP

if [ -n "$PASSWORD" ]; then
  printjs() {
      js | sed 's,//.*$,,' | tr '\n' ' '
  }

  echo "jseval -q $(printjs)" >> "$QUTE_FIFO"

  if [ -n "$TOTP" ]; then
    echo "$TOTP" | wl-copy
    notify-send "Qutebrowser 1Password" "One time password for $TITLE: $TOTP copied to clipboard" -t 3000
  fi
else
  notify-send "Qutebrowser 1Password" "No password found for $URL" -t 3000
fi
